coverage:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    status:
      project:
        default:
          target: 100%
          threshold: 50%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: unittests  #fill in your own flag name
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 50%